### ISSUE TITLE
test_enum fails with unicode character and mysqlclient on python 3

### ISSUE THREAD

**Issue by drnlm** [sqlobject/sqlobject#105]
I've now had a chance to look at this failure a bit more.

Utimately, the issue is that mysql's default character set is latin1. Forcing the character set to utf8 is enough to make the failing test pass here. 

Python 2 doesn't trigger this problem since SOCol.getDbEncoding return 'utf-8' in this case, and sqlobject encodes the data using that before passing it to MySQLdb. In the python 3 case, we are relying on mysqlclient to  encode the data, and it uses the database encoding, which then fails. Specifying 'latin1' as the charset for the connection explicitly will cause this test to fail on python 2 as well.

I'm not sure if there's a good fix for this other than documenting the behaviour on python 3 and suggesting the people specify the charset parameter accordingly when using mysql.

**Comment by phdru** [comment]
Should we change DB URI in tox.ini from
mysql://root:@localhost/sqlobject_test to
mysql://root:@localhost/sqlobject_test?charset=utf-8 ?

**Comment by drnlm** [comment]
I think that's the right thing to do for python 3.

**Comment by phdru** [comment]
Yes, that works except that charset must be utf8.
