### ISSUE TITLE
test_validation fails on Python 3

### ISSUE THREAD

**Issue by drnlm** [sqlobject/sqlobject#111]
The last test failure is test_validation, and it's also the code path responsible for the last few flake8 warnings on python 3.

StringValidator and it's subclasses check for  `__unicode__`  to test whether something should be converted to a string. This is obviously not applicable to python 3. The obvious solution is to use `__str__`, but in python 3, essentially every class has that method, so anything could be assigned to a StringCol. Consequently I'm not certain that is the right thing to do. On the other hand, I don't have a good alternative solution to this problem either.

**Comment by drnlm** [comment]
It feels a bit like a problem ABC's could be useful for, but requiring that the object supports the collections.Sequence api seems a significantly stronger requirement than the current code.

**Comment by phdru** [comment]
You're touching the central problem of porting to Python 3. There is a major semantic difference between str/unicode types in Python 2 and bytes/str types in Python 3. We have to think about the proper way.

In my opinion, StringCol and UnicodeCol in Python 3 should not deal with bytes at all, only with str. Bytes should be passed and returned by a different kind of column. BLOBCol, for example, or a special type of column.

This means that for Python 3 StringValidator, UnicodeValidator and BinaryValidator should be reworked. The first two ought to stop accepting/producing bytes, and the latter ought to accept/produce bytes and encode str to bytes using dbEncoding.

@sigmavirus24, any thoughts on this?

**Comment by drnlm** [comment]
As things currently stand, StringCol and UnicodeCol don't accept bytes on python 3, and BLOBCol mainly deals in bytes.

Other than handling a cornercase around mysql, StringValidator should fail if fed bytes. BinaryValidator arguably does the wrong thing with strings currently, but that's easy to change.

As I understand it, the issue is how to indentify 'stringlike' objects that should be allowed in a StringCol/UnicodeCol.  Custom classes which work on python2 beacuse they provide a `__unicode__` method will currently fail on python 3 because there isn't an obvious alternative check.

**Comment by phdru** [comment]
Do str instances in Python 3 belong to some Abstract Base Class(es)? If no, let's drop for some time ability to convert objects to strings — let's make string validators only accept strings, not string-like objects.

**Comment by phdru** [comment]
With my latest commits (5b03947 and a5961c7) the problem moved into FormEncode. The error now is `formencode.api.Invalid: expected a str or a unicode in the UnicodeCol 'name7', got <class 'bytes'>`. Compatibility of FormEncode with Python 3 has to be investigated.

The code is now flake8-clean even under Python 3.

**Comment by phdru** [comment]
With 18b036e all tests passed under python3!
