### ISSUE TITLE
Column 'order'

### ISSUE THREAD

**Issue by samiro** [sqlobject/sqlobject#127]
I have this table scheme on SQLITE3 file:

``` SQL
CREATE TABLE "store_topic" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(50) NOT NULL, "subject_id" integer NULL REFERENCES "store_subject" ("id"), "order" integer NOT NULL)
```

The class of object is:

``` Python
class StoreTopic(SQLObject):
    name = StringCol()
    subject_id = IntCol()
    order = IntCol()
```

On statement `topics = StoreTopic.select()` i have this error:

`OperationalError: near "order": syntax error`

I think that column 'order' it confuse with 'ORDER BY' statement.

**Comment by phdru** [comment]
```sql
sqlite> insert into store_topic (name, order) values ('test', 1);
SQLError: near "order": syntax error
```
The problem is that `order` is a keyword and must be quoted:
```sql
sqlite> insert into store_topic (name, "order") values ('test', 1);
```
but SQLObject doesn't quote names because there are too many backend-specific quoting rules.

Nobody has tried to implement even a simple quoting for SQLObject. Do you want to be the one?

**Comment by samiro** [comment]
Sure. Any clue where to start?

**Comment by phdru** [comment]
Start with [Developer Guide](http://sqlobject.org/devel/DeveloperGuide.html). The lowest level where SQL queries are generated is dbconnection.py (see how it is used in sresults.py and joins.py).

You must remember that there are at least two quoting styles — generic SQL with "double quotes" and MySQL-specific with \`backticks\`. Hence there have to be a method of DBConnection class like `def quote_name(self, name)` that will be overridden in MySQLConnection (mysql/mysqlconnection.py).

Every database has its own list of reserved keywords. I'm not sure if we should list and use them. Perhaps the simplest approach would be to quote all table and column names.

Every pull request is tested at Travis and Circle CIs.

**Comment by phdru** [comment]
Or may be not a function but an attribute of the class:
```python
class DBConnection:
    quoting_char = '"'

class MySQLConnection(DBConnection):
    quoting_char = '`'
```
