### ISSUE TITLE
INSERT row into MS SQL failed without exception

### ISSUE THREAD

**Issue by smartliukun** [sqlobject/sqlobject#130]
Hi,guys:
    I find the sqlobject is an excellent and wonderful ORM tool. Usually It worked well with MySql.

But recently,I use SqlObject to work with MS SQL.  I find sqlObject can`t insert rows to database.

the database is SQL Server 2012
the table create sql:

``` sql
CREATE TABLE [dbo].[TestTable] (
[TestTableId] int NOT NULL IDENTITY(1,1) ,
[ColName] nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL ,
CONSTRAINT [PK__TestTabl__3AE66F2450B41050] PRIMARY KEY ([TestTableId])
)
```

the test.py program as follow:

``` python
class TestTable(sqlobject.SQLObject):
    """TestTable"""
    _connection = db.connection
    class sqlmeta:
        fromDatabase = True

test_list = list(TestTable.select().limit(100))
test1 = TestTable(colName="1234dd")
print test1.colName
```

the console print  as follow:

``` sql
 1/Select  :  SELECT TOP 100 TestTable.TestTableId, TestTable.ColName FROM TestTable WHERE 1 = 1
 1/QueryR  :  SELECT TOP 100 TestTable.TestTableId, TestTable.ColName FROM TestTable WHERE 1 = 1
 1/COMMIT  :  auto
 1/QueryIns:  INSERT INTO TestTable (ColName) VALUES ('1234dd')
 1/COMMIT  :  auto
 1/QueryOne:  SELECT ColName FROM TestTable WHERE ((TestTable.TestTableId) = (293))
 1/QueryR  :  SELECT ColName FROM TestTable WHERE ((TestTable.TestTableId) = (293))
 1/COMMIT  :  auto
1234dd
```

as you see:
there is no exception and erro info .but the databse has not new row ,and IDENTITY increment !!
the IDENTITY  reseed to add 1 ,but i have not seen any rollback info.

could anybody tell me why?

Thanks.

**Comment by phdru** [comment]
Hi! That's certainly an issue with transactions. Could be an issue with autocommit. First, try setting `autocommit=1` when creating your `db.connection`. If that doesn't help execute your code inside a transaction. Replace `db.connection` with `db.connection.transaction()` or use [db.connection.doInTransaction()](http://sqlobject.org/SQLObject.html#transactions)

**Comment by smartliukun** [comment]
Thanks for your reply.

First ,i try to set connection.autocommit = True or 1, there is no effect.

Then,i replace the db.connection with db.connection.transaction() , it is worked !!! 
the code as follow:
....
class TestTable(sqlobject.SQLObject):
    """TestTable"""
    _connection = db.connection.transaction()
    class sqlmeta:
        fromDatabase = True


for i in range(10):
    TestTable(colName="aabbcc"+str(i))

TestTable._connection.commit()

The third way: db.connection.doInTransaction(). it`s also no effect and i don`t know why.

 Thanks again for your help :）
