### ISSUE TITLE
csv_import

### ISSUE THREAD

**Issue by T-bag-A** [sqlobject/sqlobject#134]
I want to try using  the module  sqlobject.util.csvexport to import csv file.
Can you pls provide some example code for that?
I have try this following code.  It can generate the class attr acorrding to the database . should the csvimport can provide the same effect?
```
class hostip(SQLObject):
    class sqlmeta:
        fromDatabase = True
```

**Comment by phdru** [comment]
It does, see the following example. File test.csv:
```csv
name:str,age:datetime,value:int
Test,2000-01-01 21:44:33,42
```
Code to load it:
```python
import csv
from sqlobject.util.csvimport import load_csv

print(load_csv(csv.reader(open('test.csv', 'rt'), delimiter=','), default_class='SQLObject'))
```
The script prints:
```
$ ./test-csv.py 
{'SQLObject': [{'age': datetime.datetime(2000, 1, 1, 21, 44, 33), 'name': 'Test', 'value': 42}]}
```
Every column has a type (in the header) and every row is a data for SQLObject tables. You can provide default class in Python or you can name classes for rows in your csv file. After that you call `create_data()` and it creates all rows in the database by creating the named classes and passing parameters from `load_csv()`. As you know the column types you can create columns before calling `create_data()`.

You can help SQLObject by extending documentation. Please send pull requests.

**Comment by phdru** [comment]
I added the example as a test_csvimport.py at a5531c8.

**Comment by T-bag-A** [comment]
thank you,
