### ISSUE TITLE
`throughTo` does not support inheritance

### ISSUE THREAD

**Issue by mpiraux** [sqlobject/sqlobject#137]
Hello,

I'm using SQLObject 3.1.0 w/ Python 3.5. It seems that SQLObject class traversal with `throughTo` does not naturally support inheritance. Let's consider the following example, adapted from the inheritance example from the docs.

```python
from sqlobject import *
from sqlobject.inheritance import InheritableSQLObject

__connection__ = "sqlite:/:memory:"

class Role(InheritableSQLObject):
    department = StringCol()

class Student(Role):
    year = IntCol()
    classroom = ForeignKey('Classroom')

class Classroom(SQLObject):
    name = StringCol()

class Professor(Role):
    timetable = StringCol(default=None)

class Person(SQLObject):
    name = StringCol()
    age = FloatCol()
    role = ForeignKey("Role", default=None)

Role.createTable()
Student.createTable()
Classroom.createTable()
Professor.createTable()
Person.createTable()

first_year = Student(department="CS", year=1, classroom=Classroom(name='A1'))
lecturer = Professor(department="Mathematics")

student = Person(name="A student", age=21, role=first_year)
professor = Person(name="A professor", age=42, role=lecturer)

Student.selectBy(year=1).throughTo.classroom.distinct()
Student.select().throughTo.classroom.distinct()
```

Executing this will raise the following error:

```python
Traceback (most recent call last):
  File "...", line 37, in <module>
    Student.select().throughTo.classroom.distinct()
  File "/usr/lib/python3.5/site-packages/sqlobject/sresults.py", line 307, in __getattr__
    return self.sresult._throughTo(attr)
  File "/usr/lib/python3.5/site-packages/sqlobject/sresults.py", line 334, in _throughTo
    self.sourceClass))
AttributeError: throughTo argument (got classroom) should be name of foreignKey or SQL*Join in <class '__main__.Role'>
```

Note that line 36 executed fine.

**Comment by phdru** [comment]
As [it's stated in the docs](http://sqlobject.org/Inheritance.html#limitations-and-notes) inheritance in SQLObject is very limited. A join is only possible with the root table of the hierarchy (`Role` in your case).

You can try to fix that but I doubt it's possible to do with a simple patch.

**Comment by mpiraux** [comment]
I've missed that part in the docs, thanks. I don't I have the time to tinker inside SQLObject, so let's consider this issue as closed/wontfix.
There are not many cases where I use inheritance + throughTo in the application I'm working on, so I will get away a few rewrites for those cases.
Thank you anyway.
