### ISSUE TITLE
Dublicate TimestampCol Error

### ISSUE THREAD

**Issue by raitaionut** [sqlobject/sqlobject#138]
Hello,
I receive error when i declare 
```
class test(SQLObject):
    created_at = TimestampCol()
    updated_at = TimestampCol()
    deleted_at = TimestampCol()
test.createTable()
```

"sqlobject.dberrors.OperationalError: Invalid default value for 'updated_at'"

If i delete update_at and deleted_at everything is ok, this will create created_at column as Timestam with default val (CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP).

I want that only update_at default val to be set as "CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP" and other 2 tbl default val as "CURRENT TIMESTAMP"

**Comment by phdru** [comment]
What's your backend? MySQL, I suppose? Mostly I use Postgres and SQLite. I'll experiment with MySQL…
