### ISSUE TITLE
autoreconnect does not work with pymysql driver

### ISSUE THREAD

**Issue by shaileshkm** [sqlobject/sqlobject#139]
Recently I started using PyMySQL as mysql driver for SQLObject since I wanted a pure python driver.

Since then, every morning any sql causes exception  in SQLobject. I have couple of questions related to it. Yesterday I updated SQLObject to latest release. Still no luck.

Stack:

  File "/home/shailesh/AuthService/Server/AuthResources.py", line 307, in GetAuthType
    product_rec = ProductTable.Product.FindKnownId(caller_product[0])
  File "/home/shailesh/AuthService/DBLib/Product.py", line 69, in FindKnownId
    if ret.count():
  File "/home/shailesh/venv-d1/local/lib/python2.7/site-packages/sqlobject/sresults.py", line 229, in count
    count = self.accumulate('COUNT(*)')
  File "/home/shailesh/venv-d1/local/lib/python2.7/site-packages/sqlobject/sresults.py", line 211, in accumulate
    return conn.accumulateSelect(self, *exprs)
  File "/home/shailesh/venv-d1/local/lib/python2.7/site-packages/sqlobject/dbconnection.py", line 501, in accumulateSelect
    val = self.queryOne(q)
  File "/home/shailesh/venv-d1/local/lib/python2.7/site-packages/sqlobject/dbconnection.py", line 476, in queryOne
    return self._runWithConnection(self._queryOne, s)
  File "/home/shailesh/venv-d1/local/lib/python2.7/site-packages/sqlobject/dbconnection.py", line 342, in _runWithConnection
    val = meth(conn, *args)
  File "/home/shailesh/venv-d1/local/lib/python2.7/site-packages/sqlobject/dbconnection.py", line 469, in _queryOne
    self._executeRetry(conn, c, s)
  File "/home/shailesh/venv-d1/local/lib/python2.7/site-packages/sqlobject/mysql/mysqlconnection.py", line 258, in _executeRetry
    raise dberrors.InterfaceError(ErrorMessage(e))
  File "/home/shailesh/venv-d1/local/lib/python2.7/site-packages/sqlobject/mysql/mysqlconnection.py", line 10, in __new__

1. The exception is coming from a constructor of ErrorMessage in sqlobject code.
Can this code be strengthened?
Found couple of threads on this topic which I need to follow up with.
https://www.mail-archive.com/sqlobject-discuss@lists.sourceforge.net/msg01213.html
http://www.boduch.ca/2009/03/ecp-and-sqlobject.html?m=0

2. What is the exception raised  in first place.
After some trial and error, found this.
 6/ERROR   :  sqlobject: **** Error in /home/shailesh/venv-d1/local/lib/python2.7/site-packages/sqlobject/mysql/mysqlconnection.py
 6/ERROR   :  query=SELECT COUNT(*) FROM product WHERE ((product.known_id) = (8193)), sqlobject error:(0, '')
 1/ERROR   :  (2006, "MySQL server has gone away (error(32, 'Broken pipe'))")

The mysql default idle connection timeout is 8 hours (wait_timeout).
So looks like, overnight, the connection from sqlobject times out.

However, this is such a basic issue to manage for ORM layer which manages connection pool. Also, never faced this  issue with mysqldb which I've been testing with for more than 4 months.

From sqlobject code, found this.
method makeConnection

                conn = self.module.connect(
                    host=self.host, port=self.port, db=self.db,
                    user=self.user, passwd=self.password, **self.kw)
                if self.driver != 'oursql':
                    # Attempt to reconnect. This setting is persistent.
                    conn.ping(True)

Found this comment in _executeRetry
	# When a server connection is lost and a query is attempted, most of
        # the time the query will raise a SERVER_LOST exception, then at the
        # second attempt to execute it, the mysql lib will reconnect and
        # succeed. However is a few cases, the first attempt raises the
        # SERVER_GONE exception, the second attempt the SERVER_LOST exception
        # and only the third succeeds. Thus the 3 in the loop count.
        # If it doesn't reconnect even after 3 attempts, while the database is
        # up and running, it is because a 5.0.3 (or newer) server is used
        # which no longer permits autoreconnects by default. In that case a
        # reconnect flag must be set when making the connection to indicate
        # that autoreconnecting is desired. In MySQLdb 1.2.2 or newer this is
        # done by calling ping(True) on the connection.

Once this exception occurs, nothing works. I have to bounce my server.
Before bouncing the server, from database I see this.

At the time of exception
MySQL [(none)]> SHOW FULL PROCESSLIST;
+-----+------+---------------------+------+---------+------+----------+-----------------------+
| Id  | User | Host                | db   | Command | Time | State    | Info
            |
+-----+------+---------------------+------+---------+------+----------+-----------------------+
| 932 | root | 172.16.100.69:53108 | NULL | Query   |    0 | starting | SHOW FULL
PROCESSLIST |
+-----+------+---------------------+------+---------+------+----------+-----------------------+

So looks like sqlobject is unable to reconnect even if it has logic to do so.

Any idea what's going wrong? Do I need to do anything explicit at caller level to enable reconnect?
Raised this issue on pymysql board also.
https://github.com/PyMySQL/PyMySQL/issues/601

**Comment by shaileshkm** [comment]
Here's what I've found so far.

- SQLObject, when creating connection, calls ping(True) on connection.
- connection has been idle for long time to have reached mysql's wait_timeout
- SQLObject issues a request
- In PyMySQL, Connection._execute_command calls Connction._write_bytes which catches exception
  - calls _force_close which closes the _sock object
  - throws OperationalError(2006, ""MySQL server has gone away")
- SQLObject catches OperationError. If one of 2006 or 2013, it reattempts query execution one more time.
- Connection._execute_command first checks if _sock object is open. If not, it throws InterfaceError.
- SQLObject has no retry logic for InterfaceError and gets tangled up when processing arg[1] (which is absent).

It looks to me, SQLObject assumption is once ping(True) is set on connection, the reconnection should be handled transparently by the driver (PyMySQL in this case). I certainly haven't seen reconnection problem with MySQLDb (mysql python) driver.

I tried doing following explicitly when handling InterfaceError in SQLObject
- Call ping again on connection
- Retry one more time

This logic did the trick.

I'm not sure if SQLObject's assumption about auto reconnect is valid or not. I guess it would be trickier doing it in db driver because, besides auto reconnect, it does not know other fact whether to do auto commit, what's the encoding etc.

In my fix, I did following when calling ping explicitly after detecting InterfaceError.
`

    def _force_reconnect(self, conn):
        msg = '***** trying to reconnect driver %s' % self.driver
        self.printDebug(conn, msg, 'ERROR')
        if self.driver.lower() in ('pymysql'):
            msg = '***** trying ping'
            self.printDebug(conn, msg, 'ERROR')
            conn.ping(True)
            msg = '***** ping successful'
            self.printDebug(conn, msg, 'ERROR')
            self._setAutoCommit(conn, bool(self.autoCommit))
            if self.dbEncoding:
                if hasattr(conn, 'set_character_set'):
                    conn.set_character_set(self.dbEncoding)
                elif hasattr(conn, 'query'):
                    conn.query("SET NAMES %s" % self.dbEncoding)

`

**Comment by shaileshkm** [comment]
There's one catch with this fix.
I'm issuing queries in transaction.
- query 1 succeeds
- idle timeout is short enough to come into effect before query 2 is executed.
- tried to execute query 2

With this fix, query 1 action will be rolled back and query 2 will succeed.
In my application,
- idle timeout is default 8 hours
- I don't have transaction behavior where distance between two queries could be so large.

**Comment by phdru** [comment]
Hi! Sorry for late answer but I'm on vacation. Will be back at the 2nd of October; but I'll be extremely busy at the job.

Thank you for investigation! SQLObject's assumption about `ping` was working for many years; the very support for PyMySQL was added not so long ago.

Can you create a pull request with your changes? They will be automatically tested. Later we can try to add tests for idle connection with and w/o transactions.
