### ISSUE TITLE
Unclear how to resolve many-to-many query

### ISSUE THREAD

**Issue by nsklld** [sqlobject/sqlobject#145]
Can you point out where in the Doc I can find an example how to resolve a Many-To-Many relationship in a query?

For example, let's say I have cars and drivers, many drivers can drive many cars. Now say I want all cars driven by "Peter".

Something like::

    cars = model.Car.select(
            AND(Car.q.drivers == Driver.q.id,
                Driver.q.name == "Peter"))
    cars = list(cars)

Does not see to make sense/work because this doesn't involve using the mapping table `car_drivers` created automatically.

I am not sure how to formulate this properly.

**Comment by phdru** [comment]
See http://sqlobject.org/SelectResults.html#traversal-to-related-sqlobject-classes

In your case the code is

    cars = Driver.select(
        Driver.q.name == "Peter").throughTo.cars

**Comment by nsklld** [comment]
beatiful!
