### ISSUE TITLE
Using augmented assignment statements

### ISSUE THREAD

**Issue by elfring** [sqlobject/sqlobject#148]
I have noticed that [source code like “`var = var + `…” was specified at a few places](https://github.com/sqlobject/sqlobject/blob/62156a3c41349b4d310fc15dc065fed17c7bf7f8/sqlobject/dbconnection.py#L107 "Update candidate: oldUri()") so far.
I suggest to [use augmented assignment statements](https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements "Augmented assignment statements") instead.

**Comment by phdru** [comment]
SQLObject was start in 2002. I don't remember if there was augmented assignment statements in Python at that time.

Anyway, I'm not going to "fix" it myself — to much work for too little gain.

You can send a pull request.
