### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [sqlobject/sqlobject#151]
I suggest to reuse a higher level build system than [your current make script](https://github.com/sqlobject/sqlobject/blob/6b889992e2ba68863aa5408446f4492c04a8c62b/docs/Makefile#L1 "Automatic generation of software documentation") so that [powerful checks for software features](https://sourceforge.net/p/sqlobject/mailman/message/36646621/ "[SQLObject] Creating database tables from queries based on ORM API?") will become easier.
- [CMake](https://cmake.org/ "Building software with CMake")
- [Autotools](https://www.gnu.org/software/autoconf/autoconf.html#introduction "Building software with Autoconf")

**Comment by phdru** [comment]
`CMake` and `Autotools` are tools for portable compilation of C/C++ code. The `Makefile` is for building docs with `Sphinx`. In what ways portable tools could help building docs? Consider that `Sphinx` is already a portable tool itself.

**Comment by elfring** [comment]
* Does [a tool like “autoscan”](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/autoscan-Invocation.html "Using autoscan to create configure.ac") show any software dependencies that you find worth for further considerations?
* How do you think about to support more development environments by [the reuse of build system generators](https://cmake.org/cmake/help/v3.14/manual/cmake-generators.7.html#cmake-generators "Listing of CMake generators")?
* Do you care for [out-of-source builds](https://gitlab.kitware.com/cmake/community/wikis/FAQ#what-is-an-out-of-source-build "What is an out-of-source build?")?

**Comment by phdru** [comment]
All these questions are completely meaningless. They have nothing with `Sphinx`. Do you know what is `Sphinx` and how SQLObject uses it?

**Comment by elfring** [comment]
>All these questions are completely meaningless.

I have got an other opinion. Can other information sources help more to accept the relevance of mentioned aspects?


>Do you know what is Sphinx and how SQLObject uses it?

[Yes](https://www.sphinx-doc.org/en/master/ "Python documentation generator"). - The use of this tool can be seen in [a make script](https://github.com/sqlobject/sqlobject/blob/6b889992e2ba68863aa5408446f4492c04a8c62b/docs/Makefile#L1 "Automatic generation of software documentation").

**Comment by phdru** [comment]
> > All these questions are completely meaningless.
> 
> I have got an other opinion.

It doesn't matter. It's just your opinion and nothing more. Show me something substantial. Show me code.

> Can other information sources help more to accept the relevance of mentioned aspects?

Nop.

> > Do you know what is Sphinx and how SQLObject uses it?
> 
> [Yes](https://www.sphinx-doc.org/en/master/). - The use of this tool can be seen in [a make script](https://github.com/sqlobject/sqlobject/blob/6b889992e2ba68863aa5408446f4492c04a8c62b/docs/Makefile#L1).

Then explain in what way you questions are related to `Sphinx`? In what way, for example, out-of-tree builds (meaningful for compiling C/C++ code) is related?

**Comment by elfring** [comment]
An out-of-tree build is supported already for the documentation of your software by passing an appropriate path with the parameter “`BUILDDIR`” to the program “`make`”.
Other software build tools can help more to choose the desired directory.

**Comment by phdru** [comment]
> An out-of-tree build is supported already for the documentation of your software by passing an appropriate path with the parameter “`BUILDDIR`” to the program “`make`”.

Yes, and what?

> Other software build tools can help more to choose the desired directory.

In what way it'd be useful?

**Comment by elfring** [comment]
* CMake supports directory selections by a file management dialogue.
* Build configurations (including the preferred output folder) can be stored in well-known formats.

**Comment by phdru** [comment]
>     * CMake supports directory selections by a file management dialogue.

We certainly don't need it. Especially when building docs completely automatically at CI.

>     * Build configurations (including the preferred output folder) can be stored in well-known formats.

We don't store any configuration so why bother at all?

And well, the question remains — why use C/C++ build tools to build reST docs? We don't need these tools. Neither for SQLObject nor for `Sphinx`-built docs.

**Comment by elfring** [comment]
>We don't store any configuration …

I came occasionally along additional needs.

>… why use C/C++ build tools to build reST docs? …

They share helpful functionality.

**Comment by phdru** [comment]
> > We don't store any configuration …

In SQLObject?

> I came occasionally along additional needs.
> 
> > … why use C/C++ build tools to build reST docs? …
> 
> They share helpful functionality.

So you don't have any real arguments. I close the question.
