### ISSUE TITLE
[want help]How to compile to raw sql ?

### ISSUE THREAD

**Issue by 625781186** [sqlobject/sqlobject#152]
When I use `createTable()`, I want to get a native SQL statement,  what should I do?

![image](https://user-images.githubusercontent.com/30521429/59616996-195a2b00-9158-11e9-9249-cfffbe1415af.png)

such as `Select()`:

![image](https://user-images.githubusercontent.com/30521429/59617352-c5037b00-9158-11e9-95cb-a1ce87ced13f.png)

**Comment by phdru** [comment]
Use [`createTableSQL`](http://sqlobject.org/api/sqlobject.main.html?highlight=createtablesql#sqlobject.main.SQLObject.createTableSQL). It returns 2-tuple `(sql, constraints)`.

PS. The issue tracker is for reporting bugs and proposing features. For generic discussions and help I recommend to subscribe to [`sqlobject-discuss` mailing list](https://sourceforge.net/p/sqlobject/mailman/).
