### ISSUE TITLE
Handling of Multiple ForeignKeys

### ISSUE THREAD

**Issue by scyclops** [sqlobject/sqlobject#153]
It appears that SQLObject is incorrectly handling some cases when a class has multiple foreign key dependencies on another class.

```python
from sqlobject import SQLObject, ForeignKey

class Person(SQLObject):
    pass

class ChatMessage(SQLObject):
    sender = ForeignKey('Person', cascade=True)
    recipient = ForeignKey('Person', cascade='null')


Person.createTable(ifNotExists=True)
ChatMessage.createTable(ifNotExists=True)

john = Person()
emily = Person()

msg = ChatMessage(sender=john, recipient=emily)

# now delete emily which should cause msg.recipient to become null
Person.delete(emily.id)
# but below are the queries that SQLObject runs
#
# > SELECT chat_message.id, chat_message.sender_id, chat_message.recipient_id
#   FROM chat_message 
#   WHERE (((chat_message.sender_id) = (2)) OR ((chat_message.recipient_id) = (2)))
# > DELETE FROM chat_message WHERE id = (1)
# > DELETE FROM person WHERE id = (2)

msg.expire()

assert msg.recipient == None
# raises SQLObjectNotFound: The object ChatMessage by the ID 1 has been deleted
```

This appears to happen because destroySelf in main.py doesn't treat each of the ForeignKey's as independent.  This causes SQLObject to erroneously group all the ForeignKeys together when deciding how to handle the cascade effects.  And when the cascade options for each ForeignKey are different (like in the example above), SQLObject doesn't apply the correct cascade effects.  This can cause data loss like the example shows.

https://github.com/sqlobject/sqlobject/blob/master/sqlobject/main.py#L1644

**Comment by phdru** [comment]
I [added tests](https://github.com/sqlobject/sqlobject/commit/14d47233fb0d8e0eb4f39c17f0ffce3b907e2910). Need to think about a fix.

**Comment by phdru** [comment]
Please test if 9c313c09 fixes the problem. The commit is not at the HEAD of branch `master` so you can just do

    pip install -U 'git+https://github.com/sqlobject/sqlobject#egg=sqlobject'

**Comment by scyclops** [comment]
I think there is a bug in test3.  When the sender is deleted, it should only cause the sender to be set to NULL.  But the new destroySelf is resulting in both the sender and the recipient being set to NULL even though the sender != the recipient.
https://github.com/sqlobject/sqlobject/blob/4b53b903b85aff4e7ee06caf1701df71ec2b7f2a/sqlobject/tests/test_ForeignKey_cascade.py#L93

I would change test3() to the below to fix the bug in the test.

```python
def test3():
    setupClass([SOTestPerson3, SOTestMessageCascadeNull])

    john = SOTestPerson3(name='john')
    emily = SOTestPerson3(name='emily')
    message = SOTestMessageCascadeNull(
        sender=emily, recipient=john, body='test3'
    )

    SOTestPerson3.delete(emily.id)
    john.expire()
    message.expire()

    john.sync()
    message.sync()
    raises(SQLObjectNotFound, emily.sync)

    assert message.sender is None
    assert message.recipient == john

    SOTestPerson3.delete(john.id)
    john.expire()
    message.expire()

    john.sync()
    message.sync()
    raises(SQLObjectNotFound, john.sync)

    assert message.recipient is None
```

**Comment by phdru** [comment]
> I think there is a bug in test3. When the sender is deleted, it should only cause the sender to be set to NULL. But the new destroySelf is resulting in both the sender and the recipient being set to NULL even though the sender != the recipient.
> 
> https://github.com/sqlobject/sqlobject/blob/4b53b903b85aff4e7ee06caf1701df71ec2b7f2a/sqlobject/tests/test_ForeignKey_cascade.py#L93
> 
>     assert message.recipient == john

Then I have to think further how to fix this in the SQLObject.

>     john.sync()
>     raises(SQLObjectNotFound, john.sync)

One or the other?

**Comment by scyclops** [comment]
> > ```
> > john.sync()
> > raises(SQLObjectNotFound, john.sync)
> > ```
> 
> One or the other?

My bad, only the raises line is needed there.  So the 2nd john.sync() call can be removed.

**Comment by phdru** [comment]
The updated commit is 852bded. Please test it or `master`. Please be warned there was a force-push.

**Comment by phdru** [comment]
@scyclops Andrew?

**Comment by scyclops** [comment]
Looks good to me.

**Comment by phdru** [comment]
Thank you for reporting!
