### ISSUE TITLE
`= ANY` does not work for postgres array membership checking

### ISSUE THREAD

**Issue by mjsir911** [sqlobject/sqlobject#154]
If I create a `Select` statement `where='value' == ANY(arrayColumn)`, it fails for postgres because
1) the `ANY()` is moved to before the `=`, and it seems to have to be after
2) the `ANY()` is placed inside of parenthesis, and that seems to not work

**Comment by phdru** [comment]
Can you create a complete test case? A table, a few rows, and `Select` or `table.select()`…

**Comment by phdru** [comment]
BTW, excessive quotes come from [`SQLOp`](https://github.com/sqlobject/sqlobject/blob/14d47233fb0d8e0eb4f39c17f0ffce3b907e2910/sqlobject/sqlbuilder.py#L307) and I don't see how to remove them. `SQLOp` almost always should add quotes and it hardly knows when it's allowed to skip them; it doesn't know its context.

**Comment by phdru** [comment]
Please try the fix a26acf96. It's currently at the head of `master` so you can try

    pip install 'git+https://github.com/sqlobject/sqlobject.git#egg=sqlobject'

**Comment by mjsir911** [comment]
This fix works, thank you very much!

**Comment by phdru** [comment]
Thank you for reporting!

**Comment by phdru** [comment]
I found a way to sqlrepr ``ALL/ANY/SOME()`` always at the right side of the comparison operation. See 4b53b90. There is no longer need in using tricks with `SQLConstant` or `SQLOp`.
