### ISSUE TITLE
CentOS 8 packaging?

### ISSUE THREAD

**Issue by siscia** [sqlobject/sqlobject#155]
Hi folks,

sqlobject is on CentOS7, but not on CentOS8

It would be usefull as well in CentOS8

**Comment by phdru** [comment]
It would be but it's not a question for us. We're the upstream, but we don't work with distributions. Any OS (like BSD) or Linux distribution (CentOS, Debian, Fedora, RedHat, whatever) are free to take our code and add to their package list.

File a request for RedHat, they now produce CentOS distribution.
