### ISSUE TITLE
columnsFromSchema no longer works on PG12

### ISSUE THREAD

**Issue by darix** [sqlobject/sqlobject#156]
`adsrc` does not exist anymore.

**Comment by phdru** [comment]
Please test commit 83fd61d. It's now at the head of branch `master` so you just do

    pip install -U git+https://github.com/sqlobject/sqlobject.git

**Comment by phdru** [comment]
Ping? No test?

**Comment by darix** [comment]
oh hi. we deployed the patch on our package and it works fine. Thank you for the fix.

**Comment by phdru** [comment]
Thank you for the report! The fix will be in the next release, 3.8 (no date, sorry). How do you prefer to be mentioned at the release notes? What about "Marcus Rückert darix-at-nordisch-dot-org" (Found in darktable-org/dtorg@23d351f0).

**Comment by darix** [comment]
not really needed. just make it "found at SUSE" :)
