### ISSUE TITLE
ForeignKey on AlternateID column

### ISSUE THREAD

**Issue by nsklld** [sqlobject/sqlobject#157]
How can I specify a ForeignKey on an **_AlternateID_** Column?

I am imagining something along the lines of
`referencingCol = ForeignKey("OtherTable.SomeUniqueCol")`
but cannot find anything in the docs.

Thanks!

**Comment by phdru** [comment]
You cannot. `ForeignKey` can only point to an `id` column.

You can try to fix that; a pull request will be welcome!

**Comment by phdru** [comment]
You may try to use [SingleJoin](http://sqlobject.org/SQLObject.html#singlejoin-one-to-one). See examples in [test_SingleJoin.py](http://sqlobject.org/_modules/sqlobject/tests/test_SingleJoin.html).
