### ISSUE TITLE
How to write where expression to match value inside JSON column.

### ISSUE THREAD

**Issue by ameyabap** [sqlobject/sqlobject#159]
Hi 
I need help in writing where expression for JSONCol field in mysql 5.7.
Example:
My class looks like:
```
class Test(sqlobject.SQLObject):
    info                      = sqlobject.JSONCol(default={})

   class sqlmeta:
        table = 'test'
```

table content could be:
 info 									|
+---------------------------------------+
{"count": 8, "name": "firstRow"}  |     

In plain sql, i would say
```
select * from test 
where info->"$.name" = "firstRow"

```
How to write the equivalent of the above query in the sqlobject expression?
How do i compare json column's internal value in sqlobject.AND() or in sqlobject.OR() expression?

I have been struggling to achieve it for a long time. Please help.

**Comment by phdru** [comment]
`JSONCol` currently doesn't support that. It only supports automatic dumping and loading.

I cannot even think about what would be an SQLObject API for such operations. Could you suggest one?

**Comment by mike1158** [comment]
I made a very minimal, hacky, python module for our own internal
      use that makes dealing with JSON columns a little bit easier. 
      We've been using it for several years, and it's held up OK.
      
      I'm attaching it here in case it might be useful as-is if your
      needs are not great, or maybe as just a discussion point for a
      better implementation.
      
      Cheers,
      -Mike
    
    On 9/3/20 12:55 PM, Oleg Broytman
      wrote:
    
    
      
      JSONCol currently doesn't support that. It only
        supports automatic dumping and loading.
      I cannot even think about what would be an SQLObject API for
        such operations. Could you suggest one?
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/sqlobject/sqlobject/issues/159#issuecomment-686722058",
"url": "https://github.com/sqlobject/sqlobject/issues/159#issuecomment-686722058",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by phdru** [comment]
> I'm attaching it here

I don't see an attachment. Perhaps GitHub cut it from incoming email.

**Comment by mike1158** [comment]
On 9/3/20 2:14 PM, Oleg Broytman wrote:
    
      
      
        I'm attaching it here
      
      I don't see an attachment. Perhaps GitHub cut it from incoming
        email.
    
    
    Apologies, I was afraid that might happen.  Unfortunately, don't
    have the time to make a proper PR, so I just copy/pasted it below
    since it's not that much code.
    
    -Mike
    
    
    -------
    
    """
    JSON Column for SQLObject
    
Notes:
    
    * Data is automatically converted to/from Python data types supported by
          Python's own json module.
    
    * IMPORTANT: Changing a field's data directly does NOT update the database.
          This is because SQLObject works by hooking the assignment of the column
          property itself.  If you want to change the data, do it like so:
    
          tmp = someTable.someJsonColumn
              tmp['key'] = 'newvalue'
              someTable.someJSONColumn = tmp
    
    * SQL queries can be done on the data within the JSON column with
          SQLObject's normal query mechanism with the following extensions:
    
        - Compare a members's value:
    
          Table.q.column.json_extract("key") == value
    
        - Test existance of an item in a JSON array (does NOT apply to JSON
              object names):
    
          Table.q.column.json_contains("item")
    
    * See http://dev.mysql.com/doc/refman/5.7/en/json-functions.html
    
"""
    
import json
    
import six
    
from sqlobject import *
    from sqlobject.col import StringValidator
    from formencode import validators
    
__all__ = ["JSONCol"]
    

    #############################################
    #
    # Begin code from SQLObject 3.1
    #
    
class JSONValidator(StringValidator):
    
    def to_python(self, value, state):
            if value is None:
                return None
            if isinstance(value, six.string_types):
                return json.loads(value)
            raise validators.Invalid(
                "expected a JSON str in the JSONCol '%s', "
                "got %s %r instead" % (
                    self.name, type(value), value), value, state)
    
    def from_python(self, value, state):
            if value is None:
                return None
            if isinstance(value,
                          (bool, float, dict, list) + six.string_types + six.integer_types):
                return json.dumps(value)
            raise validators.Invalid(
                "expected an object suitable for JSON in the JSONCol '%s', "
                "got %s %r instead" % (
                    self.name, type(value), value), value, state)
    

    class SOJSONCol(SOStringCol):
    
    def createValidators(self):
            return [JSONValidator(name=self.name)] + \
                super(SOJSONCol, self).createValidators()
    
    def _sqlType(self):
            return 'JSON'
    

    class JSONCol(StringCol):
        baseClass = SOJSONCol
    
#
    # End of code from SQLObject 3.1
    #
    #############################################
    

    #############################################
    #
    # Added by Tippett
    #
    
#
    # Convenience stuff Monkey-Patched onto sqlbuilder.SQLObjectField,
    # so you can do:
    #
    #   Table.q.column.json_extract("key") == value
    #   Table.q.column.json_contains("item")
    #   Table.q.column.json_length("key")
    #
    # instead of
    #
    #   func.JSON_EXTRACT(Table.q.column, '$.key') == value
    #   func.JSON_CONTAINS(Table.q.column, json.dumps("item"))
    #   func.JSON_LENGTH(Table.q.column, '$.key')
    #
    
def _json_extract(col, key, path=None):
        """
        """
        assert isinstance(col.column, SOJSONCol), "{!r} is not a JSONCol".format(col)
        if path is None:
            return func.JSON_EXTRACT(col, '$.%s' % key)
        else:
            return func.JSON_EXTRACT(col, '$.%s' % key, path)
    
def _json_contains(col, value, path=None):
        assert isinstance(col.column, SOJSONCol), "{!r} is not a JSONCol".format(col)
        if path is None:
            return func.JSON_CONTAINS(col, json.dumps(value))
        else:
            return func.JSON_CONTAINS(col, json.dumps(value), path)
    
def _json_length(col, path=None):
        assert isinstance(col.column, SOJSONCol), "{!r} is not a JSONCol".format(col)
        if path is None:
            return func.JSON_LENGTH(col)
        else:
            return func.JSON_LENGTH(col, path)
    
sqlbuilder.SQLObjectField.json_extract = _json_extract
    sqlbuilder.SQLObjectField.json_contains = _json_contains
    sqlbuilder.SQLObjectField.json_length = _json_length

**Comment by phdru** [comment]
> Unfortunately, don't have the time to make a proper PR, so I just copy/pasted it below since it's not that much code. -Mike

Thanks, now it's here!

**Comment by ameyabap** [comment]
Great. Thanks a lot @mike1158 @phdru. 
@mike1158 I will add the changes in local `sqlobject-3.7.0/sqlobject/col.py` and test it. I will update the outcome here. 
Any plans on pushing the code in the repo?

**Comment by phdru** [comment]
> Any plans on pushing the code in the repo?

Depends on the outcome of your tests. Please report if the thing works for you. Even better — create a pull request.

**Comment by ameyabap** [comment]
Hi @mike1158 @phdru 
I am getting "SQLObjectField instance has no attribute 'json_extract'" when I use it like `rows.filter(sqlobject.AND((getattr(Table.q, "info").json_extract("name") == "firstRow")))`

Attaching git diff for col.py. Let me know whether it is correct addition of @mike1158 's code
json was already imported in a file.
```
--- a/contrib/sqlobject-3.7.0/sqlobject/col.py
+++ b/contrib/sqlobject-3.7.0/sqlobject/col.py
@@ -18,6 +18,8 @@ So, in summary: Col objects are what you define, but SOCol objects
 are what gets used.
 """
 
+from sqlobject.col import StringValidator
+from formencode import validators
 from array import array
 from decimal import Decimal
 from itertools import count
@@ -2006,6 +2008,62 @@ class JSONCol(StringCol):
     baseClass = SOJSONCol
 
 
+    #
+    # End of code from SQLObject 3.1
+    #
+    #############################################
+
+
+    #############################################
+    #
+    # Added by Tippett
+    #
+
+    #
+    # Convenience stuff Monkey-Patched onto sqlbuilder.SQLObjectField,
+    # so you can do:
+    #
+    #   Table.q.column.json_extract("key") == value
+    #   Table.q.column.json_contains("item")
+    #   Table.q.column.json_length("key")
+    #
+    # instead of
+    #
+    #   func.JSON_EXTRACT(Table.q.column, '$.key') == value
+    #   func.JSON_CONTAINS(Table.q.column, json.dumps("item"))
+    #   func.JSON_LENGTH(Table.q.column, '$.key')
+    #
+__all__ = ["JSONCol"]
+
+def _json_extract(col, key, path=None):
+        """
+        """
+        assert isinstance(col.column, SOJSONCol), "{!r} is not a JSONCol".format(col)
+        if path is None:
+            return func.JSON_EXTRACT(col, '$.%s' % key)
+        else:
+            return func.JSON_EXTRACT(col, '$.%s' % key, path)
+
+def _json_contains(col, value, path=None):
+        assert isinstance(col.column, SOJSONCol), "{!r} is not a JSONCol".format(col)
+        if path is None:
+            return func.JSON_CONTAINS(col, json.dumps(value))
+        else:
+            return func.JSON_CONTAINS(col, json.dumps(value), path)
+
+def _json_length(col, path=None):
+        assert isinstance(col.column, SOJSONCol), "{!r} is not a JSONCol".format(col)
+        if path is None:
+            return func.JSON_LENGTH(col)
+        else:
+            return func.JSON_LENGTH(col, path)
+
+sqlbuilder.SQLObjectField.json_extract = _json_extract
+sqlbuilder.SQLObjectField.json_contains = _json_contains
+sqlbuilder.SQLObjectField.json_length = _json_length
+
+
+
 def pushKey(kw, name, value):
     if name not in kw:
         kw[name] = value
@@ -2017,3 +2075,4 @@ for key, value in globals().copy().items():
         all.append(key)
 __all__.extend(all)
 del all
+

```

**Comment by ameyabap** [comment]
Even I tried adding these 3 json methods as public methods of SQLObjectField class but still, I am getting `SQLObjectField instance has no attribute 'json_extract` error. @mike1158 Can you check for any missing pieces in my git diff?

**Comment by phdru** [comment]
@mike1158, @ameyabap Please see the branch jsoncol. 3 commits: fce8a9a, 73dd7e4 and a8462fe.

See successful runs at https://travis-ci.org/github/sqlobject/sqlobject/builds/726783567 and https://ci.appveyor.com/project/phdru/sqlobject/builds/35178195.

Mike, `_sqlType() -> 'JSON'` makes tests fail so I commented it out. See the test runs at https://travis-ci.org/github/sqlobject/sqlobject/builds/726780961 and https://ci.appveyor.com/project/phdru/sqlobject/builds/35178075/job/2tlvpfjjkjbda739.

**Comment by ameyabap** [comment]
Cool. I will check it.

**Comment by phdru** [comment]
I fixed most of the problems with `JSONCol` and its validator; see the branch `jsoncol`. They still have problems with some drivers though. Please look at https://travis-ci.org/github/sqlobject/sqlobject/builds/745097674.

There are problems under MySQL with `oursql` driver. Other drivers are ok

There are problems under Postgres with `psycopg`, `pygresql`, and `pg8000` drivers. `pypostgresql` drivers is ok.

IWBN if someone looks at the tracebacks and suggests what to fix — SQLObject or drivers.

**Comment by phdru** [comment]
Nobody lent a hand so I'm going to comment out `_sqlType()` and merge.
