### ISSUE TITLE
DateCol getting AttributeError

### ISSUE THREAD

**Issue by zSeriesGuy** [sqlobject/sqlobject#161]
I defined a DateCol() column. When I create the object, it is throwing an AttributeError 'str' object has no attribute 'seconds' in col.py at 1272 in the DataTimeValidator class.

Using SQLite database.

```
class CalendarEvent(SQLObject):
    class sqlmeta:
        style = MixedCaseStyle()
        table = 'CalendarEvents'
    Name = StringCol(unique=True, notNone=True)
    Startday = DateCol(notNone=True)

```
I'm creating the object with:
`            calEv1 = CalendarEvent(Name='CalEvent1', Startday=datetime.datetime(year=2020, month=11, day=3))
`But it also throws the same exception if I use Startday='2020-11-3'.
Same error if I define the column as DateTimeCol().

The row does get inserted into the table.

This is on Windows 10 with Python 3.7.5 using SQLObject 3.8.1 under pyCharm. 
 I do not have mx installed.

**Comment by phdru** [comment]
> ```
> class CalendarEvent(SQLObject):
>     class sqlmeta:
>         style = MixedCaseStyle()
>         table = 'CalendarEvents'
>     Name = StringCol(unique=True, notNone=True)
>     Startday = DateCol(notNone=True)
> ```
> 
> I'm creating the object with:
> ` calEv1 = CalendarEvent(Name='CalEvent1', Startday=datetime.datetime(year=2020, month=11, day=3))`But it also throws the same exception if I use Startday='2020-11-3'.

I cannot reproduce the problem:

    $ cat test1.py

    #! /usr/bin/env python
    # -*- coding: utf-8 -*-

    from sqlobject import *
    from sqlobject.inheritance import *
    from sqlobject.sqlbuilder import *
    from sqlobject.versioning import *
    import datetime

    __connection__ = "sqlite:/:memory:?debug=1&debugOutput=1"

    class CalendarEvent(SQLObject):
        class sqlmeta:
            style = MixedCaseStyle()
            table = 'CalendarEvents'
        Name = StringCol(unique=True, notNone=True)
        Startday = DateCol(notNone=True)

    CalendarEvent.createTable()
    calEv1 = CalendarEvent(Name='CalEvent1', Startday=datetime.datetime(year=2020, month=11, day=3))
    calEv2 = CalendarEvent(Name='CalEvent2', Startday='2020-11-3')

    $ mktmpenv -p python3.8

    $ pip install SQLObject

    $ python --version
    Python 3.8.6

    $ python test1.py
     1/Query   :  CREATE TABLE CalendarEvents (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        Name TEXT NOT NULL UNIQUE,
        Startday DATE NOT NULL
    )
     1/QueryR  :  CREATE TABLE CalendarEvents (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        Name TEXT NOT NULL UNIQUE,
        Startday DATE NOT NULL
    )
     2/QueryIns:  INSERT INTO CalendarEvents (Name, Startday) VALUES ('CalEvent1', '2020-11-03')
     2/QueryR  :  INSERT INTO CalendarEvents (Name, Startday) VALUES ('CalEvent1', '2020-11-03')
     2/QueryIns-> 1
     3/QueryOne:  SELECT Name, Startday FROM CalendarEvents WHERE ((CalendarEvents.id) = (1))
     3/QueryR  :  SELECT Name, Startday FROM CalendarEvents WHERE ((CalendarEvents.id) = (1))
     3/QueryOne-> ('CalEvent1', '2020-11-03')
     4/QueryIns:  INSERT INTO CalendarEvents (Name, Startday) VALUES ('CalEvent2', '2020-11-03')
     4/QueryR  :  INSERT INTO CalendarEvents (Name, Startday) VALUES ('CalEvent2', '2020-11-03')
     4/QueryIns-> 2
     5/QueryOne:  SELECT Name, Startday FROM CalendarEvents WHERE ((CalendarEvents.id) = (2))
     5/QueryR  :  SELECT Name, Startday FROM CalendarEvents WHERE ((CalendarEvents.id) = (2))
     5/QueryOne-> ('CalEvent2', '2020-11-03')

Everything is ok.

> I defined a DateCol() column. When I create the object, it is throwing an AttributeError 'str' object has no attribute 'seconds' in col.py at 1272 in the DataTimeValidator class.

The error is quite strange. The code [`col.py`:1272](https://github.com/sqlobject/sqlobject/blob/270dd73d1d0a6db0abc453bf74743189151d8a08/sqlobject/col.py#L1272) is under [`if isinstance(value, TimeType)`](https://github.com/sqlobject/sqlobject/blob/270dd73d1d0a6db0abc453bf74743189151d8a08/sqlobject/col.py#L1269) so `value` here certainly cannot be a string.
 
> Using SQLite database.
> 
> ```
> class CalendarEvent(SQLObject):
>     class sqlmeta:
>         style = MixedCaseStyle()
>         table = 'CalendarEvents'
>     Name = StringCol(unique=True, notNone=True)
>     Startday = DateCol(notNone=True)
> ```
> 
> I'm creating the object with:
> ` calEv1 = CalendarEvent(Name='CalEvent1', Startday=datetime.datetime(year=2020, month=11, day=3))`But it also throws the same exception if I use Startday='2020-11-3'.
> Same error if I define the column as DateTimeCol().
> 
> The row does get inserted into the table.
> 
> This is on Windows 10 with Python 3.7.5 using SQLObject 3.8.1 under pyCharm.
> I do not have mx installed.

Also very strange. The `if` checks if the value is an instance if `mx.Time`.

**Comment by zSeriesGuy** [comment]
Using your code, I tested again with Py 3.7.5 and it still failed with the same error.
I installed Py 3.8.6, what you used, and it worked fine. 
So the issue seems to be related to Python 3.7.5.

**Comment by zSeriesGuy** [comment]
I created a new venv for 3.7.5 and only install sqlobject and it worked.
So the issue has to do with some other package I have installed that might be conflicting.
I'll research to see if I can figure it out.
Thanks for looking at this.

**Comment by zSeriesGuy** [comment]
So perhaps my venv was corrupt or something. Just installed all the packages I originally had into this new 3.7.5 venv and it all works. geez. Sorry about that.

**Comment by zSeriesGuy** [comment]
I figured out what breaks it.
I installed a package called icalevents. This installs another package called zope.interface.
It breaks.
When I remove zope.interface, it works again.

**Comment by phdru** [comment]
Thank you for reporting! I will investigate…

**Comment by phdru** [comment]
Also not reproducible:

    $ mktmpenv -p python3.7

    (tmp-3324af415f33293c) $ pip install SQLObject zope.interface
    Successfully installed FormEncode-2.0.0 PyDispatcher-2.0.5 SQLObject-3.8.1 six-1.15.0 zope.interface-5.2.0

    (tmp-3324af415f33293c) $ ./test1.py 
     1/Query   :  CREATE TABLE CalendarEvents (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        Name TEXT NOT NULL UNIQUE,
        Startday DATE NOT NULL
    )
     1/QueryR  :  CREATE TABLE CalendarEvents (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        Name TEXT NOT NULL UNIQUE,
        Startday DATE NOT NULL
    )
     2/QueryIns:  INSERT INTO CalendarEvents (Name, Startday) VALUES ('CalEvent1', '2020-11-03')
     2/QueryR  :  INSERT INTO CalendarEvents (Name, Startday) VALUES ('CalEvent1', '2020-11-03')
     2/QueryIns-> 1
     3/QueryOne:  SELECT Name, Startday FROM CalendarEvents WHERE ((CalendarEvents.id) = (1))
     3/QueryR  :  SELECT Name, Startday FROM CalendarEvents WHERE ((CalendarEvents.id) = (1))
     3/QueryOne-> ('CalEvent1', '2020-11-03')
     4/QueryIns:  INSERT INTO CalendarEvents (Name, Startday) VALUES ('CalEvent2', '2020-11-03')
     4/QueryR  :  INSERT INTO CalendarEvents (Name, Startday) VALUES ('CalEvent2', '2020-11-03')
     4/QueryIns-> 2
     5/QueryOne:  SELECT Name, Startday FROM CalendarEvents WHERE ((CalendarEvents.id) = (2))
     5/QueryR  :  SELECT Name, Startday FROM CalendarEvents WHERE ((CalendarEvents.id) = (2))
     5/QueryOne-> ('CalEvent2', '2020-11-03')

**Comment by zSeriesGuy** [comment]
I think I have it figured out what to install to recreate the issue.
I had installed icalevents. This brings in a package called DateTime.
I did some further testing and determined that it is the installation of DateTime package that causes the issue.
So just pip install SQLObject DateTime and see if that will recreate the issue.

**Comment by phdru** [comment]
> a package called DateTime.

Oh, `DateTie` from `zope`. I've had [a bug report about it](https://sourceforge.net/p/sqlobject/bugs/206/) but I though it was fixed long ago. It seems I need to go back to it and add more fixes and tests.

**Comment by phdru** [comment]
Can you try your code with SQLObject from the branch `DateTime`, commit 5d53827?

**Comment by zSeriesGuy** [comment]
It works great. No errors. Thank you.

**Comment by phdru** [comment]
Thank your for head up and for testing!
