### ISSUE TITLE
Descending databaseindex

### ISSUE THREAD

**Issue by zSeriesGuy** [sqlobject/sqlobject#162]
When using DatabaseIndex to build an  index, is there any way to specify descending on one or more of the keys? Or do I need to use createSQL?

**Comment by phdru** [comment]
Please reread http://sqlobject.org/SQLObject.html#indexes. You can use any SQL expression: `DatabaseIndex({'expression': 'name DESC'})`.

PS. Github issues is hardly a good support forum. Next time try [the mailing list](http://sqlobject.org/community.html) or [StackOverflow](https://stackoverflow.com/questions/tagged/sqlobject).
