### ISSUE TITLE
Custom column

### ISSUE THREAD

**Issue by bronte2k7** [sqlobject/sqlobject#164]
Hi @phdru

I want to make PasswordCol for generate password hash. But I don't understand how to implement my own column. Please show me an example

**Comment by bronte2k7** [comment]
helped me: http://www.sqlobject.org/SQLObject.html#overriding-column-attributes

**Comment by phdru** [comment]
See the implementation of HashCol: https://github.com/sqlobject/sqlobject/blob/master/sqlobject/include/hashcol.py It's almost ready to be a password column.

**Comment by bronte2k7** [comment]
Thanks for your reply. I decided to use _set and _get it's even more convenient
