### ISSUE TITLE
feature request: versioning table name

### ISSUE THREAD

**Issue by bronte2k7** [sqlobject/sqlobject#165]
Hi @phdru

```python
class AccountTable(Table):
    email = StringCol(length=512, notNone=True, unique=True)
    password = StringCol(length=512, notNone=True)
    versions = Versioning()

    class sqlmeta:
        table = 'account'

```
version table name: account_table_versions

I would like to be able to specify my name for the version table. Because sometimes the final name is not very convenient.

**Comment by phdru** [comment]
1st, such requests should be discussed in [the mailing list](https://sourceforge.net/projects/sqlobject/lists/sqlobject-discuss). David Turner who has implemented versioning is unavailable but there are other people.

2nd, this feature [was implemented](https://github.com/sqlobject/sqlobject/commit/976ebcaa19950cc4b31c5e003e2249b7c65a5f5c#diff-31267ed9c7e9b0a50d49e80d1dccb4073f142a730fec191ca38b61459900b6fa) long ago and I never looked into the code. Just did it now for the first time.

3rd, do you want to try to implement it? AFAIU the [name is generated](https://github.com/sqlobject/sqlobject/blob/df7ad69dca4d25021b0f07f90aac075b38d20227/sqlobject/versioning/__init__.py#L87) as a class name and later `Style` object converts it to 'lowercase_with_underscore' style. So my advice for an implementation is: add an optional parameter `name=None` to [`Versioning.__init__`](https://github.com/sqlobject/sqlobject/blob/df7ad69dca4d25021b0f07f90aac075b38d20227/sqlobject/versioning/__init__.py#L66) and rewrite [type's name](https://github.com/sqlobject/sqlobject/blob/df7ad69dca4d25021b0f07f90aac075b38d20227/sqlobject/versioning/__init__.py#L87) as `self.name or elf.soClass.__name__ + 'Versions'`. Please also add a [test](https://github.com/sqlobject/sqlobject/tree/master/sqlobject/versioning/test).

**Comment by bronte2k7** [comment]
Thanks for your reply. Well, when there is a choice :)

**Comment by phdru** [comment]
Closed for inactivity.
