### ISSUE TITLE
RelatedJoin: Expand table

### ISSUE THREAD

**Issue by bronte2k7** [sqlobject/sqlobject#168]
Hi

I am using this example: http://www.sqlobject.org/SQLObject.html#relatedjoin-and-sqlrelatedjoin-many-to-many
I need to add columns for the assigned_roles table, is this possible?

**Comment by drnlm** [comment]
This is an issue tracker for sqlobject, not a help forum - there are better avenues to getting answers to your questions - see http://sqlobject.org/community.html

**Comment by bronte2k7** [comment]
> This is an issue tracker for sqlobject, not a help forum - there are better avenues to getting answers to your questions - see http://sqlobject.org/community.html

I know this is not a forum. But I am asking the question because this information is not in the documentation - this is problem

**Comment by bronte2k7** [comment]
The issue is resolved
