### ISSUE TITLE
feature request: field method between two numeric values

### ISSUE THREAD

**Issue by bronte2k7** [sqlobject/sqlobject#170]
Hi @phdru

Very useful method. There is no such thing in the documentation

**Comment by phdru** [comment]
I don't understand. Can you provide a code example of the proposed feature?

**Comment by bronte2k7** [comment]
SQL query:
```sql
SELECT *
FROM table_name
WHERE column_name BETWEEN value1 AND value2;
```
Python:
```python
User.q.balance.between(value1, value2)
```
This is a field method, same as startswith or endswith

**Comment by phdru** [comment]
Ok, I see: [MySQL](https://dev.mysql.com/doc/refman/5.7/en/comparison-operators.html#operator_between), [Postgres](https://www.postgresql.org/docs/9.5/functions-comparison.html) and [SQLite](https://sqlite.org/lang_expr.html#between). You can implement it similar to [operator `IN`](https://github.com/sqlobject/sqlobject/blob/b21d76a239533d8b126b4ceb162dfb7c04fee60b/sqlobject/sqlbuilder.py#L1455-L1471) (or any other operator in SQLBuilder).

**Comment by bronte2k7** [comment]
Of course, in this case, I can use SQLBuilder. But the field method looks much more convenient)))

**Comment by phdru** [comment]
Can be implemented the same way as `User.q.name.startswith(prefix)` (also `endswith()` and `contains()`) [are implemented](https://github.com/sqlobject/sqlobject/blob/b21d76a239533d8b126b4ceb162dfb7c04fee60b/sqlobject/sqlbuilder.py#L460-L470).

**Comment by bronte2k7** [comment]
Goodly. This is the most convenient way))). Is it possible to extend the SQLObjectField class yourself? There are more methods that can be added for convenience.

p.s. thanks for your reply

**Comment by phdru** [comment]
> Is it possible to extend the SQLObjectField class yourself? There are more methods that can be added for convenience.

What do you want to extend?

Anyway my advice is to start small. 1st, implement `between`, add documentation and tests.

**Comment by bronte2k7** [comment]
Hi @phdru

I would like to add more methods for the field. These methods are needed solely for the convenience. An example of some methods: [http://docs.peewee-orm.com/en/latest/peewee/query_operators.html#query-operators](here). 

Of course, good documentation and tests are very important)))

**Comment by phdru** [comment]
Closed for inactivity.
