### ISSUE TITLE
Forcing Sequential Scans on PostgreSQL Via Use of Large Integers

### ISSUE THREAD

**Issue by jeremyevans** [sqlobject/sqlobject#181]
First, I apologize for posting what could be considered a potential security issue directly in a public bug tracker.  I could not find instructions for submitting reports of potential security issues in SQLObject.

Applications using SQLObject are potentially vulnerable to the issue described in https://code.jeremyevans.net/2022-11-01-forcing-sequential-scans-on-postgresql.html.

Assuming you create the following table in a PostgreSQL Database:

```sql
CREATE TABLE bs AS SELECT * FROM generate_series(1,1000000) AS a(id);
CREATE INDEX ON bs(id);
```

You can see a dramatic difference in performance in the two queries at the bottom:

```python
import sqlobject
import timeit
sqlobject.sqlhub.processConnection = sqlobject.connectionForURI('postgres://...')
class BS(sqlobject.SQLObject):
  ""

t = sqlobject.sqlbuilder.table.bs
print(timeit.timeit(lambda: BS.select().filter(t.id == 2**63-1).getOne(None), number=10))
print(timeit.timeit(lambda: BS.select().filter(t.id == 2**63).getOne(None), number=10))
```

My recommendation would be for SQLObject to take the approach I took in Sequel, raising an exception when literalizing Python integers outside PostgreSQL bigint range, maybe with a configuration option to switch to either quoting or allowing the values (the equivalent of the pg_extended_integer_support Sequel extension).  However, be aware that such an approach is not backwards compatible if users are using large Python integers and relying on them being converted to numeric types by PostgreSQL.

**Comment by phdru** [comment]
Thank you for reporting. I don't think it's really a security issue. I'm not even sure it should be fixed in SQLObject and not in applications that use SQLObject.
