### ISSUE TITLE
getOne(None) still raises SQLObjectNotFound  even though doc says it should not

### ISSUE THREAD

**Issue by Kaju-Bubanja** [sqlobject/sqlobject#183]
I have following query: `film = Film.selectBy(stop_timestamp=None).orderBy('-start_timestamp').getOne(None)` and it raised a `sqlobject.main.SQLObjectNotFound: The object Film by the ID 0 does not exist` exception, even though [the docs](http://www.sqlobject.org/SelectResults.html#getone-default-optional) say it should not raise an exception

**Comment by phdru** [comment]
I cannot reproduce the problem. The following program
```python
#! /usr/bin/env python

from sqlobject import *
from sqlobject.sqlbuilder import *

__connection__ = "sqlite:/:memory:?debug=1"

class Test(SQLObject):
    name = StringCol(default=None)

Test.createTable()
print(Test.select().getOne(None))
```
produces output:
```text
 1/Query   :  CREATE TABLE test (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT
)
 1/QueryR  :  CREATE TABLE test (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT
)
 2/Select  :  SELECT test.id, test.name FROM test WHERE 1 = 1
 2/QueryR  :  SELECT test.id, test.name FROM test WHERE 1 = 1
None
```
Everything seem to be ok. Can you please provide a test case to reproduce the problem?

**Comment by Kaju-Bubanja** [comment]
Blimey, I didn't save the stacktrace nowhere. I will let you know the exact version this happened in next week and might also find the stacktrace again. But it happened in production so I unfortunately can't provide you an example. But the stacktrace had the exact line I mentioned above with getOne(None) and also the exact error I wrote. I will come back to you with the affected version.

**Comment by Kaju-Bubanja** [comment]
Alright I found the stacktrace:

```
[2022-12-15 08:04:10,270: ERROR/ForkPoolWorker-3] Task app_name_celery.tasks.current_film_task[dc629092-8c76-4cf6-a82e-065dccca5d33] raised unexpected: SQLObjectNotFound('The object Film by the ID 0 does not exist',)I│
│Traceback (most recent call last):                                                                                                                                                                               │
│  File "/home/username/app/lib/python3.6/site-packages/celery/app/trace.py", line 450, in trace_task                                                                                                                  │
│    R = retval = fun(*args, **kwargs)                                                                                                                                                                            │
│  File "/home/username/app/lib/python3.6/site-packages/celery/app/trace.py", line 731, in __protected_call__                                                                                                          │
│    return self.run(*args, **kwargs)                                                                                                                                                                             │
│  File "/home/username/app/app_name-celery/app_name_celery/tasks.py", line 774, in current_film_task                                                                                                        │
│    current_film(config, info)                                                                                                                                                           │
│  File "/home/username/app/app_name-module/app_name_module/generate.py", line 518, in current_film                                                                                                            │
│    film = Film.selectBy(stop_timestamp=None).orderBy('-start_timestamp').getOne(None)                                                                                                                           │
│  File "/home/username/app/lib/python3.6/site-packages/sqlobject/sresults.py", line 288, in getOne                                                                                                                    │
│    results = list(self)                                                                                                                                                                                         │
│  File "/home/username/app/lib/python3.6/site-packages/sqlobject/sresults.py", line 189, in __iter__                                                                                                                  │
│    return iter(list(self.lazyIter()))                                                                                                                                                                           │
│  File "/home/username/app/lib/python3.6/site-packages/sqlobject/dbconnection.py", line 762, in __next__                                                                                                              │
│    return self.next()                                                                                                                                                                                           │
│  File "/home/username/app/lib/python3.6/site-packages/sqlobject/dbconnection.py", line 778, in next                                                                                                                  │
│    connection=self.dbconn)                                                                                                                                                                                      │
│  File "/home/username/app/lib/python3.6/site-packages/sqlobject/main.py", line 943, in get                                                                                                                           │
│    val._init(id, connection, selectResults)                                                                                                                                                                     │
│  File "/home/username/app/lib/python3.6/site-packages/sqlobject/main.py", line 985, in _init                                                                                                                         │
│    self.__class__.__name__, self.id))                                                                                                                                                                           │
│sqlobject.main.SQLObjectNotFound: The object Film by the ID 0 does not exist
```

and the affected sqlobjects version is: 3.9.1

**Comment by Kaju-Bubanja** [comment]
It seems to happen from other contexts as well, in very strange places:

```
│2022-12-16 16:31:07,971.971 ERROR celery.app.trace:trace.py:267 Task app_name_celery.tasks.current_film_task[a3cbe191-28aa-4fae-a8dc-25755e848a92] raised unexpected: SQLObjectNotFound('The object Infraction by the ID 0 does not exist│
│Traceback (most recent call last):                                                                                                                                                                               │
│  File "/home/username/app/lib/python3.6/site-packages/celery/app/trace.py", line 450, in trace_task                                                                                                                  │
│    R = retval = fun(*args, **kwargs)                                                                                                                                                                            │
│  File "/home/username/app/lib/python3.6/site-packages/celery/app/trace.py", line 731, in __protected_call__                                                                                                          │
│    return self.run(*args, **kwargs)                                                                                                                                                                             │
│  File "/home/username/app/app_name-celery/app_name_celery/tasks.py", line 774, in current_film_task                                                                                                        │
│    current_film(config, info)                                                                                                                                                     │
│  File "/home/username/app/app_name-module/app_name_module/generate.py", line 543, in current_film                                                                                                            │
│    for infraction in infractions:                                                                                                                                                                               │
│  File "/home/username/app/lib/python3.6/site-packages/sqlobject/sresults.py", line 189, in __iter__                                                                                                                  │
│    return iter(list(self.lazyIter()))                                                                                                                                                                           │
│  File "/home/username/app/lib/python3.6/site-packages/sqlobject/dbconnection.py", line 762, in __next__                                                                                                              │
│    return self.next()                                                                                                                                                                                           │
│  File "/home/username/app/lib/python3.6/site-packages/sqlobject/dbconnection.py", line 778, in next                                                                                                                  │
│    connection=self.dbconn)                                                                                                                                                                                      │
│  File "/home/username/app/lib/python3.6/site-packages/sqlobject/main.py", line 943, in get                                                                                                                           │
│    val._init(id, connection, selectResults)                                                                                                                                                                     │
│  File "/home/username/app/lib/python3.6/site-packages/sqlobject/main.py", line 985, in _init                                                                                                                         │
│    self.__class__.__name__, self.id))                                                                                                                                                                           │
│sqlobject.main.SQLObjectNotFound: The object Infraction by the ID 0 does not exist

```
and infractions is defined as:
```
infractions = Infraction.selectBy(processed=False).filter(
        (Infraction.q.timestamp >= film.start_timestamp) &
        (Infraction.q.timestamp <= arrow.utcnow().shift(minutes=-1).float_timestamp) &
        (Infraction.q.skipped == False)
    ).orderBy('timestamp')[:10]
```

together with this issue we've been seeing other strange issues like 

`formencode.api.Invalid: ("expected a str in the StringCol 'some_column', got <class 'int'> 42 instead", 42, '<sqlobject.sqlbuilder.SQLObjectState object at 0x7f2b67d46b70>', None, None)`
and
`formencode.api.Invalid: ("expected a str in the StringCol 'some_totally_differend column in another object', got <class 'int'> 42 instead", 42, '<sqlobject.sqlbuilder.SQLObjectState object at 0x7f2b67d46b70>', None, None)`

but when I check the database the columns have the right type and value. It's as if the orm got desynced from the database. Is that somehow a possibility?

**Comment by phdru** [comment]
The traceback doesn't help much because it doesn't show what is in the DB.

> │    film = Film.selectBy(stop_timestamp=None).orderBy('-start_timestamp').getOne(None)                                                                                                                           │
> │  File "/home/username/app/lib/python3.6/site-packages/sqlobject/sresults.py", line 288, in getOne                                                                                                                    │
> │    results = list(self)                                                                                                                                                                                         │
> │  File "/home/username/app/lib/python3.6/site-packages/sqlobject/sresults.py", line 189, in __iter__                                                                                                                  │
> │    return iter(list(self.lazyIter()))                                                                                                                                                                           │
> │  File "/home/username/app/lib/python3.6/site-packages/sqlobject/dbconnection.py", line 762, in __next__                                                                                                              │
> │    return self.next()                                                                                                                                                                                           │
> │  File "/home/username/app/lib/python3.6/site-packages/sqlobject/dbconnection.py", line 778, in next                                                                                                                  │

This part of the traceback clearly shows SQLObject extracted something from the DB:

> │    connection=self.dbconn)                                                                                                                                                                                      │
> │  File "/home/username/app/lib/python3.6/site-packages/sqlobject/main.py", line 943, in get                                                                                                                           │
> │    val._init(id, connection, selectResults)                                                                                                                                                                     │
> │  File "/home/username/app/lib/python3.6/site-packages/sqlobject/main.py", line 985, in _init                                                                                                                         │
> │    self.__class__.__name__, self.id))                                                                                                                                                                           │
> │sqlobject.main.SQLObjectNotFound: The object Film by the ID 0 does not exist
> ```

But that something is invalid and have `id=0`. Could it be you temporary put a dummy row into DB with `id=0` and then remove it but SQLObject tries to get it?

> and the affected sqlobject version is: 3.9.1

My simple test program above passes, no problem. I'm afraid you need to create a small test case with code and a DB to demonstrate the problem.

**Comment by Kaju-Bubanja** [comment]
Yeah I thought the same thing that something is inserted and then later deleted, but our code in that area did not change and we generally don't delete the objects out of the db at all. I understand that this is hard to debug with just the stacktraces and no complete example and no db data. But unfortunately we also can't reproduce it in tests, it just sporadically happens in live systems. The slight difference is that we use more cpu and memory in live. Could increased cpu/ram usage be related to the id=0 issue? I know I'm grasping for straws, but not much else that I can do atm.

**Comment by phdru** [comment]
> together with this issue we've been seeing other strange issues like
> 
> `formencode.api.Invalid: ("expected a str in the StringCol 'some_column', got <class 'int'> 42 instead", 42, '<sqlobject.sqlbuilder.SQLObjectState object at 0x7f2b67d46b70>', None, None)` and `formencode.api.Invalid: ("expected a str in the StringCol 'some_totally_differend column in another object', got <class 'int'> 42 instead", 42, '<sqlobject.sqlbuilder.SQLObjectState object at 0x7f2b67d46b70>', None, None)`
> 
> but when I check the database the columns have the right type and value. It's as if the orm got desynced from the database. Is that somehow a possibility?

Could be that int `42` comes from the code, not from the DB? In the test program above: add
```python
Test(name=42)
```
and the traceback is
```
Traceback (most recent call last):
  File "./test-42.py", line 12, in <module>
    Test(name=42)
  File "/home/phd/.local/lib/python2.7/site-packages/sqlobject/main.py", line 1301, in __init__
    self._create(id, **kw)
  File "/home/phd/.local/lib/python2.7/site-packages/sqlobject/main.py", line 1349, in _create
    self.set(**kw)
  File "/home/phd/.local/lib/python2.7/site-packages/sqlobject/main.py", line 1146, in set
    self._SO_validatorState)
  File "/home/phd/.local/lib/python2.7/site-packages/sqlobject/col.py", line 617, in to_python
    self.name, type(value), value), value, state)
formencode.api.Invalid: expected a str in the StringCol 'name', got <type 'int'> 42 instead
```

**Comment by Kaju-Bubanja** [comment]
Then again, I think the original issue is still valid and no exception should be generated for the line: `film = Film.selectBy(stop_timestamp=None).orderBy('-start_timestamp').getOne(None)` based on the docs. Do you agree?

**Comment by Kaju-Bubanja** [comment]
The expected a str issue happens on the last line here:
```
open_films = Film.selectBy(stop_timestamp=None).orderBy('start_timestamp')
if open_films.count() < 1:
    return

current_film = open_films[-1]
```
which is very odd, because nowhere is the 42 in the code not even as a variable could it be there.

**Comment by phdru** [comment]
> Then again, I think the original issue is still valid and no exception should be generated for the line: `film = Film.selectBy(stop_timestamp=None).orderBy('-start_timestamp').getOne(None)` based on the docs. Do you agree?

No. `.getOne(None)` doesn't raise exceptions if there is nothing to select. It raises the exception when `Film.selectBy()` returns something but `.getOne(None)` cannot fetch that from the DB. That surely an error condition to report to the user, it shouldn't be ignored.

**Comment by phdru** [comment]
> The expected a str issue happens on the last line here:
> 
> ```
> open_films = Film.selectBy(stop_timestamp=None).orderBy('start_timestamp')
> if open_films.count() < 1:
>     return
> 
> current_film = open_films[-1]
> ```
> 
> which is very odd, because nowhere is the 42 in the code not even as a variable could it be there.

Well, you know what to do — write a test case demonstrating the problem.

**Comment by Kaju-Bubanja** [comment]
> > Then again, I think the original issue is still valid and no exception should be generated for the line: `film = Film.selectBy(stop_timestamp=None).orderBy('-start_timestamp').getOne(None)` based on the docs. Do you agree?
> 
> No. `.getOne(None)` doesn't raise exceptions if there is nothing to select. It raises the exception when `Film.selectBy()` returns something but `.getOne(None)` cannot fetch that from the DB. That surely an error condition to report to the user, it shouldn't be ignored.

I see, so the select and the getOne are distinct operations inbetween which the db can change.

**Comment by phdru** [comment]
Wild guess — you run the code under Celery so it opens a different connection and a new transaction from the main program. Your code could be sensitive to the order of transaction beginning/committing/rolling back.
