### ISSUE TITLE
duckdb support

### ISSUE THREAD

**Issue by davetapley** [sqlobject/sqlobject#184]
Is there interest in [duckdb](https://duckdb.org/) support?

> The standard DuckDB Python API provides a SQL interface compliant with the [DB-API 2.0 specification described by PEP 249](https://www.python.org/dev/peps/pep-0249/) similar to the [SQLite Python API](https://docs.python.org/3.7/library/sqlite3.html).

https://duckdb.org/docs/api/python/overview

Probably wouldn't be _too_ hard?

---

Just for fun I tried seeing if I could load one with `connectionForURI('sqlite:'` but:
```
sqlobject.dberrors.DatabaseError: file is not a database
```

**Comment by phdru** [comment]
> Is there interest in [duckdb](https://duckdb.org/) support?

Sure.

> Probably wouldn't be _too_ hard?

Do you want to send a pull request?

> Just for fun I tried seeing if I could load one with `connectionForURI('sqlite:'` but:
> 
> ```
> sqlobject.dberrors.DatabaseError: file is not a database
> ```

Wrong URI. See http://sqlobject.org/SQLObject.html#declaring-a-connection
