### ISSUE TITLE
sqlcipher support

### ISSUE THREAD

**Issue by shuffleyxf** [sqlobject/sqlobject#189]
Is there interest in [sqlcipher](https://github.com/sqlcipher/sqlcipher) support?

> SQLCipher is a standalone fork of the [SQLite](https://www.sqlite.org/) database library that adds 256 bit AES encryption of database files and other security features.

If so, I'd like to contibute.

**Comment by phdru** [comment]
Interesting. Any contributions are welcome.

AFAIU there will be a new driver? I'd like to ask a minimal docs; at least DB URI syntax.

Tests: the test suite must pass, so please run it locally; do necessary additions in `tox.ini`. What minimal version of Python are you going to support? SQLObject supports 2.7 and 3.4+. I very much hope you can support these Python version or at least 3.6+.

**Comment by phdru** [comment]
Please follow https://sqlobject.org/DeveloperGuide.html#style-guide

**Comment by phdru** [comment]
@shuffleyxf Any progress?
