### ISSUE TITLE
Does SQLObject suffer of the problem of useless order by on some ORM prefetches ?

### ISSUE THREAD

**Issue by LLyaudet** [sqlobject/sqlobject#190]
Hello,

Recently I found a problem with Django and submitted a patch in a PR:
https://code.djangoproject.com/ticket/35309
https://github.com/django/django/pull/17984
I also developped a work-around for old versions of Django:
https://github.com/LLyaudet/django-monkey-patches/blob/main/src/django_monkey_patches/django__orm__prefetch_without_useless_order_by.py

I don't know yet SQLObject details.
The idea is just that some models can have a default ordering (I assume this functionality is present in SQLObject also).
And that some ORM may still add this ordering in the SQL query whilst it is not needed because only a single object will be prefetched per instance of the original result set.
On very big prefetches I noticed a gain of 10 - 15 %,
since the rest of the DB query is mainly an index scan.
#ClimateChangeBrake

Can someone please dump the queries of such prefetches and see if the bug is present in SQLObject ?
If so submitting a PR should not be too hard.
I will try to help.
But right now, I start by warning the frameworks/ORM I am aware of :)

Best regards,
      Laurent Lyaudet

**Comment by phdru** [comment]
Hello! Thanks for heads up. But...

> I don't know yet SQLObject details.

I'm afraid that's the biggest issue with the issue.

> The idea is just that some models can have a default ordering (I assume this functionality is present in SQLObject also). And that some ORM may still add this ordering in the SQL query whilst it is not needed because only a single object will be prefetched per instance of the original result set.

AFAIU you mean if one declares a table

    class MyTable(SQLObject):
        class sqlmeta:
            orderBy = 'name'
        name = StringCol()

and fetches the data from DB as `row = MyTable.get(42)` then excessive `orderBy` would slow down the query, right?

> Can someone please dump the queries of such prefetches

Who'd be that "someone"? I suspect I'm the only one who watch issues and pull requests here. Github issues is hardly a good forum. You can try [the mailing list](https://sourceforge.net/projects/sqlobject/lists/sqlobject-discuss), there is *probably* a bigger audience.

> and see if the bug is present in SQLObject ?

Well, I'm sure there isn't. There're 3 ways to get SQLObject instances:

- construct it from data: `row = MyTable(name='Foo')`;
- get a single row from the DB: `row = MyTable.get(42)`;
- get a list of rows: `for row in MyTable.select(condition): …`

Only the last one uses `orderBy` in the query. So no bug in the first two. If I'm wrong *someone* (and that someone is actually you) should prove me wrong with a small test case.

**Comment by LLyaudet** [comment]
Hello @phdru :)
Thanks for your answer.
From what you say, you must not have the issue because it is linked to prefetches:

```
class MyTable(SQLObject):
    class sqlmeta:
        orderBy = 'name'
    name = StringCol()

class MyTable2(SQLObject):
    class sqlmeta:
        orderBy = 'name'
    name = StringCol()
    // insert some foreign key to MyTable here (I don't know the syntax)
```
```
for row in MyTable2.select(condition).prefetch(@linked_rows_of_MyTable@):
```
If the prefetch uses the default ordering of MyTable,
it is this bug since the ordering is not needed to fill a single value in the cache of the foreign key of MyTable elements.

Best regards,
     Laurent Lyaudet

**Comment by phdru** [comment]
Aha, foreign keys, I see. SQLObject doesn't do multi-row prefetch for foreign keys, it resolves every access to a foreign key separately. But the code there *could* pass `ORDER BY defaultOrder` to the backend. That claim I have to acknowledge or reject. Thinking…

**Comment by phdru** [comment]
Test case:
```python
#! /usr/bin/env python

from sqlobject import *

__connection__ = "sqlite:/:memory:?debug=1&debugOutput=1"

class Person(SQLObject):
    class sqlmeta:
        table = 'city_person'
        defaultOrder = 'name'
    name = StringCol()

class Animal(SQLObject):
    class sqlmeta:
        table = 'city_animal'
        defaultOrder = 'name'
    name = StringCol()
    owner = ForeignKey('Person')

Person.createTable()
Animal.createTable()

person = Person(name='Test')
cat = Animal(name='Kitty', owner=person)

print(Person.select())
print(Animal.select())

Person._connection.cache.clear()
print(cat.owner)
```

```python
print(Person.select())
print(Animal.select())
```
are used to test `defaultOrder` works. It does, SQL queries are:
```sql
SELECT city_person.id, city_person.name FROM city_person WHERE 1 = 1 ORDER BY city_person.name
SELECT city_animal.id, city_animal.name, city_animal.owner_id FROM city_animal WHERE 1 = 1 ORDER BY city_animal.name
```
`ORDER BY` is there, ok.

```python
Person._connection.cache.clear()  # Force SQL query
print(cat.owner)
```
SQL query for the foreign key is
```sql
SELECT name FROM city_person WHERE ((city_person.id) = (1))
```
No `ORDER BY` here. Seems to be ok. Case closed?

**Comment by LLyaudet** [comment]
Yes, case closed I think, if as you said SQLObject doesn't do multi-row prefetch for foreign keys, I see no othercase to check :)
