### ISSUE TITLE
`RowUpdatedSignal` is not send after update.

### ISSUE THREAD

**Issue by AntonChak** [sqlobject/sqlobject#193]
Hello there!

I faced with the issue that the signal `RowUpdatedSignal` is not called after `.set()` call, while the docstring says that it should.
<img width="590" alt="image" src="https://github.com/user-attachments/assets/3eba4125-9fb7-4edd-98fd-6ef4f9474535">

 Documentation suggests to use `lazyUpdate=True` option (otherwise it stucks in other signals), but `set` method has if statement which checks if `lazyUpdate` is True and there is a return inside this statement. The signal is called at the end of `set` and only if this statement had not passed the required condition.
<img width="624" alt="image" src="https://github.com/user-attachments/assets/1cdbc086-6aee-4ccf-843b-746d08a73d1e">

My question:
Is this a bug or documentation mistake? How can I retrieve this signal after the update in both cases `.set` and direct attribute set and `.syncUpdate()`.
Seems, there is missing signal sending before return. If it is not `_creating`.

**Comment by phdru** [comment]
I do not fully understand the problem. At the beginning of `set()` there is the code https://github.com/sqlobject/sqlobject/blob/32c1ce111d56025594083a8c8889994f205acc9c/sqlobject/main.py#L1126-L1129 . If the signal is not sent which of the conditions is not `True` in your case? Can you provide a short test script to demonstrate the problem?

PS. Please do not use images. Next time please copy/paste code and format it as code block. Images are hard to read and impossible to copy or search.

**Comment by AntonChak** [comment]
Thank you for the reply! I will try to use links and describe everything better in this comment :)

There are two different [signals](https://github.com/sqlobject/sqlobject/blob/32c1ce111d56025594083a8c8889994f205acc9c/sqlobject/events.py#L143C1-L161C8) on update action:
1) `RowUpdateSignal` (e.g. before update)
2) `RowUpdatedSignal` (e.g. after update)

The code snippet you've shared is before update signal and it's working just fine. 
The issue is that after update signal is not sent, when `.set()` is called. [This if statement](https://github.com/sqlobject/sqlobject/blob/32c1ce111d56025594083a8c8889994f205acc9c/sqlobject/main.py#L1148C1-L1178C19) will be executed next, just because we have set `sqlmeta.lazyUpdate = True` according to the documentation (from the signal's docstrings). This code ends up with `return`. And in my case `self.sqlmeta.dirty = True` hadn't made any black box magic. I didn't receive `RowUpdatedSignal` after update.

While `.set()` without `lazyUpdate` option ends up with sending the [actual signal](https://github.com/sqlobject/sqlobject/blob/32c1ce111d56025594083a8c8889994f205acc9c/sqlobject/main.py#L1227C1-L1230C23). 

I was not investigating deeply what is happening in between, but in any case both signals should be send on update.
I've used a kinda hotfix, but it feels it should be included in the package:
```
class MyTable(SQLObject):
    class sqlmeta:
        ...
        lazyUpdate = True
    ...
    
    def set(self, *args, **kwargs):
        super().set(*args, **kwargs)
        if (
            not self.sqlmeta._creating
            and self.sqlmeta.lazyUpdate
            and not kwargs.get('_suppress_set_sig')
        ):
            post_funcs = []
            self.sqlmeta.send(RowUpdatedSignal, self, post_funcs)
            for post_func in post_funcs:
                post_func(self)
```

**Comment by phdru** [comment]
Oh, it's `RowUpdatedSignal`, not `RowUpdateSignal`!

Well, with `lazyUpdate` set to `True` `.set()` shouldn't send the signal because
1) the row is not updated yet, `UPDATE` query was not sent to the backend, only the instance in memory is updated;
2) `syncUpdate()` will send the signal, there is no need to send it twice.

**Comment by AntonChak** [comment]
Ah, I see yeah. You are right :) 
I forgot that `lazyUpdate` is lazy and it's required to call some sync function. 

Thank you for the reply.
