### ISSUE TITLE
Attempting to access ConnectionHub.threadConnection throws AttributeError

### ISSUE THREAD

**Issue by kkartaltepe** [sqlobject/sqlobject#55]
Calling `sqlhub.threadConnection == None` will result in `AttributeError: type object 'thread._local' has no attribute 'connection'` if you have not set the threadConnection.

I believe a good resolution would be by safely accessing the connection attribute of thread._local by replacing https://github.com/sqlobject/sqlobject/blob/master/sqlobject/dbconnection.py#L966
with a safe accessor like `getattr(self.threadingLocal, 'connection', None)` to allow a user to check the state of the threadConnection.

I am trying to do this because I want to create new connection for every thread in a framework where I don't have control over what thread my code will be called in (or when these treads will be created). Mainly because SQLite doesnt play well with a shared connection across all the threads so using `processConnection` just results in SQLite complaining about objects being created in different threads.

(Let me know if there is a better place to raise this question/issue)

**Comment by phdru** [comment]
If you haven't set an attribute to an object you don't usually expect you can get the attribute from the object, right? In such case you use hasattr() instead of testing the attribute:

```python
hasattr(sqlhub, 'threadConnection') # => False
```

Can you use `hasattr()` in your case?

PS. Github issue tracker is good enough for issues.

**Comment by kkartaltepe** [comment]
That works! Thanks a bunch.

I guess I'm too used to other languages.
