### ISSUE TITLE
sqlmeta class has no attribute soClass

### ISSUE THREAD

**Issue by sigmavirus24** [sqlobject/sqlobject#77]
https://travis-ci.org/sqlobject/sqlobject/jobs/50224733#L220

**Comment by drnlm** [comment]
The syntax for metaclasses changed significantly between python 2 and python 3, so the setup operations that depend on metaclasses doesn't currently run on pthon 3.

There are multiple approaches to fixing this - the easiest is probably to add a dependancy on six and use its add_metaclass decorator.

**Comment by sigmavirus24** [comment]
If we're going to add a dependency on `six` for anything other than `add_metaclass` then I'm :+1: but otherwise, can we just vendor that function? Last time I looked at it, it was roughly 5 or 6 lines of code and was pretty simple.

**Comment by drnlm** [comment]
To get a better feel for the situation, I've hack'ishly done a port to python 3 ignoring backwards compatability at https://github.com/drnlm/sqlobject/tree/py3k_scratch_space  - it still fails a handful of tests, and hacks the handling of unicode and blob columns, something we'll need to look at carefully when doing the proper port, but does give an idea of the remaining issues.

Other than the metaclass helper, it's mainly the basestring / str / unicode renaming that looks painful to support across the chosen set of python versions. It's probably not enough to justify the extra dependency.

**Comment by phdru** [comment]
> https://github.com/drnlm/sqlobject/tree/py3k_scratch_space

How interesting!

> it's mainly the basestring / str / unicode renaming

I have always though str/unicode incompatibilities are the biggest problems when porting something to Py3.

> that looks painful to support across the chosen set of python versions.

Do you recommend to drop Py 2.6? Or 2.7 (and hence 2 completely)?

**Comment by sigmavirus24** [comment]
It's definitely plausible to do support 2.6, 2.7, 3.4 (and then 3.3 and 3.2) It will be hard work, but we can definitely do it. We'll just need to sit down and make sure we all know what type is supposed to be where and when.

For one thing, I really don't like Python 2 but dropping it completely is not something we should even bother considering at this point. 2.6 is plausible to drop with RHEL releasing new versions that use 2.7 as the lowest common denominator. Regardless, there are still lots of people stuck on 2.5 and 2.6 still because of LTS releases of Ubuntu and Debian. Personally, I don't think it's fair to abandon them outright (regardless of how superior a language Python 3 is).

**Comment by drnlm** [comment]
I think it's far too early to talk about dropping python 2, even though it would simplify things a lot.

Dropping 2.6 would simplify a few bits of the port, but it's not a huge gain, so I don't think there's a strong argument to do so.

**Comment by lukmdo** [comment]
how about #80 ?
